// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXkLoin3RoNAqwmZs52qyGRZ0UBUum1kY',
    appId: '1:450696520816:web:99839ae4bcc374988540b5',
    messagingSenderId: '450696520816',
    projectId: 'admiral-taxi',
    authDomain: 'admiral-taxi.firebaseapp.com',
    databaseURL: 'https://admiral-taxi-default-rtdb.firebaseio.com',
    storageBucket: 'admiral-taxi.appspot.com',
    measurementId: 'G-ZPJ148WF0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJBPyZ15FwNmAjbaXAvbMwwbv1fiZAkg',
    appId: '1:450696520816:android:54196e51eeaee72e8540b5',
    messagingSenderId: '450696520816',
    projectId: 'admiral-taxi',
    databaseURL: 'https://admiral-taxi-default-rtdb.firebaseio.com',
    storageBucket: 'admiral-taxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6HZ3MD1p-SCQ75qdPhM81IsUXfK9Qjo',
    appId: '1:450696520816:ios:7f6da0c49402bbdf8540b5',
    messagingSenderId: '450696520816',
    projectId: 'admiral-taxi',
    databaseURL: 'https://admiral-taxi-default-rtdb.firebaseio.com',
    storageBucket: 'admiral-taxi.appspot.com',
    iosBundleId: 'com.example.admiralTaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6HZ3MD1p-SCQ75qdPhM81IsUXfK9Qjo',
    appId: '1:450696520816:ios:81bf368459831e238540b5',
    messagingSenderId: '450696520816',
    projectId: 'admiral-taxi',
    databaseURL: 'https://admiral-taxi-default-rtdb.firebaseio.com',
    storageBucket: 'admiral-taxi.appspot.com',
    iosBundleId: 'com.example.admiralTaxi.RunnerTests',
  );
}
